imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:           %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'], assets_version: %assets_version% }
    default_locale:  %locale%
    trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [KachkaevPhotoAssessmentBundle]
    java: %java_bin%
    filters:
        cssrewrite: ~
        closure:
           jar: %kernel.root_dir%/Resources/java/compiler.jar
#            api: ~
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

doctrine_migrations:
    table_name:           MigrationVersions

lunetics_locale:
  allowed_locales:
    - en
    - ru
  guessing_order:
    - cookie
    - router
    - browser

bazinga_geocoder:
    providers:
        ip_info_db:
            api_key:    %api_key_ipinfodb%
        free_geo_ip: ~

kachkaev_counters:
    disabled: %kernel.debug%
    google_analytics:
      id: UA-19190359-3
    yandex_metrika: ~

kachkaev_dropbox_backup:
    database:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        
        output_directory: pat-db/
        output_fileprefix: %database_dropbox_prefix%
        output_compression: true
    dropbox:
        user: %dropbox_user%
        password: %dropbox_password%
        
#kachkaev_assets_version: ~

# Swiftmailer Configuration
#swiftmailer:
#    transport: %mailer_transport%
#    host:      %mailer_host%
#    username:  %mailer_user%
#    password:  %mailer_password%
#    spool:     { type: memory }