parameters:
    pat.queue_first_photo_id: -1
    pat.queue_initial_size: 50
    pat.queue_extension_size: 25
    pat.geograph_dir: %kernel.root_dir%/../web/content/geograph
    pat.ask_location: false
    pat.survey_closed: true
    pat.results.show_test_photo: false
    pat.results.max_submitted_at: ~
        # 1358183114 #14 Jan 
        # 1359219914 # 26 Jan
    pat.photos_location_grid.path: %kernel.root_dir%/../src/Kachkaev/PhotoAssessmentBundle/Resources/config/photos_location_grid.yml